var urlBasePaladins = "https://api.paladins.com/paladinsapi.svc/";
var urlBaseSmite = "https://api.smitegame.com/smiteapi.svc/";
var urlBaseLOL = 'https://euw1.api.riotgames.com/lol/';
exports.riotAPIKEY = process.env.RIOT_API_KEY;
exports.hirezAPIKEY = process.env.HIREZ_API_KEY;
exports.hirezAUTHKEY = process.env.HIREZ_AUTH_KEY;
exports.urlBasePaladins = urlBasePaladins;
exports.urlBaseSmite = urlBaseSmite;
exports.urlBaseLOL = urlBaseLOL;
